don't use nursery since it will update with WIP lints
e.g.

```
error: this could be a `const fn`
367
   --> cli/src/reporter.rs:375:1
368
    |
369
375 | / fn get_violations_emoji(count: usize) -> &'static str {
370
376 | |     if count > 0 {
371
377 | |         "🚒"
372
378 | |     } else {
373
379 | |         "✅"
374
380 | |     }
375
381 | | }
376
    | |_^
377
    |
378
    = note: `-D clippy::missing-const-for-fn` implied by `-D clippy::nursery`
379
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#missing_const_for_fn
    ```