Update Nix flake with newer nixpkgs version (#287)
I tried building Squawk recently in the Nix development shell and was running into a `cargo build` issue due to an older rustc version coming from nixpkgs: "error[E0658]: `let...else` statements are unstable". I see that the rust-toolchain is now using 1.67.0 and nixpkgs is providing 1.61.0.

I ran `nix flake update` to get newer pinned versions of nixpkgs and the flake-utils library (not really important for this problem). I also had to override the version of libpg_query that comes through nixpkgs because it isn't compatible with Squawk. Upon making these changes, `nix develop` and `nix build` work correctly again.